spring:
  application:
    name: Open mHealth shim server
  # this is necessary to prevent proxy errors due https://github.com/spring-projects/spring-boot/issues/1929
  dao:
    exceptiontranslation:
      enabled: false
  data:
    mongodb:
      uri: mongodb://mongo:27017/omh_dsu
  jackson:
    serialization:
      indent_output: true
server:
  port: 8083
security:
  basic:
    enabled: false
logging:
  file: omh-shims.log

openmhealth:
  shim:
    server:
      callbackUrlBase: http://localhost:8083

    #NOTE: Un-comment and fill in with your credentials if you're not using the UI
    #fitbit:
    #  partner_access: true
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #fatsecret:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #ihealth:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #jawbone:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #misfit:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #runkeeper:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #withings:
    #  partner_access: true
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #healthvault:
    #  clientId: [YOUR_CLIENT_ID]
    #googlefit:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
